package com.example.practice7.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3A5BA9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDAE2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001847)
val md_theme_light_secondary = Color(0xFF6C4EA2)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEBDCFF)
val md_theme_light_onSecondaryContainer = Color(0xFF270058)
val md_theme_light_tertiary = Color(0xFF006973)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF91F1FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F23)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF2FFFD)
val md_theme_light_onBackground = Color(0xFF00201E)
val md_theme_light_surface = Color(0xFFF2FFFD)
val md_theme_light_onSurface = Color(0xFF00201E)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
val md_theme_light_outline = Color(0xFF757780)
val md_theme_light_inverseOnSurface = Color(0xFFB1FFF8)
val md_theme_light_inverseSurface = Color(0xFF003734)
val md_theme_light_inversePrimary = Color(0xFFB2C5FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF3A5BA9)
val md_theme_light_outlineVariant = Color(0xFFC5C6D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB2C5FF)
val md_theme_dark_onPrimary = Color(0xFF002B73)
val md_theme_dark_primaryContainer = Color(0xFF1E4390)
val md_theme_dark_onPrimaryContainer = Color(0xFFDAE2FF)
val md_theme_dark_secondary = Color(0xFFD4BBFF)
val md_theme_dark_onSecondary = Color(0xFF3D1C70)
val md_theme_dark_secondaryContainer = Color(0xFF543588)
val md_theme_dark_onSecondaryContainer = Color(0xFFEBDCFF)
val md_theme_dark_tertiary = Color(0xFF4ED8E9)
val md_theme_dark_onTertiary = Color(0xFF00363C)
val md_theme_dark_tertiaryContainer = Color(0xFF004F57)
val md_theme_dark_onTertiaryContainer = Color(0xFF91F1FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF00201E)
val md_theme_dark_onBackground = Color(0xFF70F7EE)
val md_theme_dark_surface = Color(0xFF00201E)
val md_theme_dark_onSurface = Color(0xFF70F7EE)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
val md_theme_dark_outline = Color(0xFF8F909A)
val md_theme_dark_inverseOnSurface = Color(0xFF00201E)
val md_theme_dark_inverseSurface = Color(0xFF70F7EE)
val md_theme_dark_inversePrimary = Color(0xFF3A5BA9)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB2C5FF)
val md_theme_dark_outlineVariant = Color(0xFF45464F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF3A5BA9)